version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/nginx:latest

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build -t petespangler/canadianwealthassessment:$CIRCLE_SHA1 .

      - run:
          name: Push Docker image
          command: |
            echo -n DOCKER_PASSWORD | docker login -u DOCKERHUB_USERNAME --password-stdin
            docker push petespangler/canadianwealthassessment:$CIRCLE_SHA1
